version: "1"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - /home/vagrant/mysql/data:/var/lib/mysql

  spring_app:
    image: tahersn/skistation:latest
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
    ports:
      - 8089:8089
    depends_on:
      - mysqldb