version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_HOST="%"
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: youssefalmia/5twin5-g7-skistation:latest
    container_name: SkiStation
    restart: on-failure
    networks:
      - mynetwork
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=user
      - spring.datasource.password=pwd
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

networks:
  mynetwork:
    driver: bridge
